@echo off
echo Installing dependencies...
call npm install

echo Starting infrastructure...
docker-compose up -d

echo Waiting for database...
timeout /t 5 /nobreak

echo Running migrations...
call npx prisma migrate dev --name init

echo Starting dev server...
call npm run dev
